//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PiriChainWalletDataBridge {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang_tr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang_tr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PiriChainWalletDataBridge.lang_tr", typeof(lang_tr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Ekle.
        /// </summary>
        internal static string addNew {
            get {
                return ResourceManager.GetString("addNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        internal static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres Defteri.
        /// </summary>
        internal static string addressBook {
            get {
                return ResourceManager.GetString("addressBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miktar.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varlık.
        /// </summary>
        internal static string AssetName {
            get {
                return ResourceManager.GetString("AssetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İptal.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onay.
        /// </summary>
        internal static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onay Sayısı.
        /// </summary>
        internal static string confirmationCount {
            get {
                return ResourceManager.GetString("confirmationCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} adres defteri silienecek. Emin misin?.
        /// </summary>
        internal static string confirmDelete {
            get {
                return ResourceManager.GetString("confirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onaylı.
        /// </summary>
        internal static string confirmed {
            get {
                return ResourceManager.GetString("confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Cüzdan Oluştur.
        /// </summary>
        internal static string createNewAddress {
            get {
                return ResourceManager.GetString("createNewAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Şifre Oluştur.
        /// </summary>
        internal static string createNewPassword {
            get {
                return ResourceManager.GetString("createNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Şifreyi Giriniz.
        /// </summary>
        internal static string enterNewPassword {
            get {
                return ResourceManager.GetString("enterNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Şifreyi Tekrar Giriniz.
        /// </summary>
        internal static string enterNewPasswordAgain {
            get {
                return ResourceManager.GetString("enterNewPasswordAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm Alanları Doldurunuz!.
        /// </summary>
        internal static string errFillAllFields {
            get {
                return ResourceManager.GetString("errFillAllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetersiz Bakiye.
        /// </summary>
        internal static string errInsufficientBalance {
            get {
                return ResourceManager.GetString("errInsufficientBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata!.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre En Az 5 Karakter Olmalı!.
        /// </summary>
        internal static string errorMustbeLeast5Ch {
            get {
                return ResourceManager.GetString("errorMustbeLeast5Ch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreler Aynı Değil!.
        /// </summary>
        internal static string errorPasswordNotMatched {
            get {
                return ResourceManager.GetString("errorPasswordNotMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yanlış Şifre!.
        /// </summary>
        internal static string errWrongPass {
            get {
                return ResourceManager.GetString("errWrongPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pirichain Cüzdan ve Veri Yükleme Sistemi.
        /// </summary>
        internal static string frmEntrance_LblTitle {
            get {
                return ResourceManager.GetString("frmEntrance_LblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreniz.
        /// </summary>
        internal static string frmEntrance_lblYourPassword {
            get {
                return ResourceManager.GetString("frmEntrance_lblYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etiket.
        /// </summary>
        internal static string label {
            get {
                return ResourceManager.GetString("label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil.
        /// </summary>
        internal static string lang {
            get {
                return ResourceManager.GetString("lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkında.
        /// </summary>
        internal static string menuAbout {
            get {
                return ResourceManager.GetString("menuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres Defteri.
        /// </summary>
        internal static string menuAddressBook {
            get {
                return ResourceManager.GetString("menuAddressBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cüzdan Ekle.
        /// </summary>
        internal static string menuAddWallet {
            get {
                return ResourceManager.GetString("menuAddWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veritabanı.
        /// </summary>
        internal static string menuDatabase {
            get {
                return ResourceManager.GetString("menuDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cüzdan Sil.
        /// </summary>
        internal static string menuDeleteWallet {
            get {
                return ResourceManager.GetString("menuDeleteWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cüzdan Seç.
        /// </summary>
        internal static string menuSelectWallet {
            get {
                return ResourceManager.GetString("menuSelectWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piri Koin Veya Token Gönder.
        /// </summary>
        internal static string menuSendCoin {
            get {
                return ResourceManager.GetString("menuSendCoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cüzdanlar.
        /// </summary>
        internal static string menuWallet {
            get {
                return ResourceManager.GetString("menuWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres Başarıyla Eklendi!.
        /// </summary>
        internal static string messageAddressAdded {
            get {
                return ResourceManager.GetString("messageAddressAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres Başarıyla Düzenlendi!.
        /// </summary>
        internal static string messageAddressUpdated {
            get {
                return ResourceManager.GetString("messageAddressUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Başarıyla Gerçekleşti!.
        /// </summary>
        internal static string messageTransferSucc {
            get {
                return ResourceManager.GetString("messageTransferSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Cüzdan Eklendi. Cüzdan Bölümünde Yeni Cüzdanınızı Seçebilirsiniz..
        /// </summary>
        internal static string msgWalletAddedSucc {
            get {
                return ResourceManager.GetString("msgWalletAddedSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamam.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alıcı Adresi.
        /// </summary>
        internal static string receipt {
            get {
                return ResourceManager.GetString("receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cüzdanımı Kurtar.
        /// </summary>
        internal static string RescueMyWallet {
            get {
                return ResourceManager.GetString("RescueMyWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonuç.
        /// </summary>
        internal static string result {
            get {
                return ResourceManager.GetString("result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onayla.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoşgeldiniz.
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bakiyeniz:.
        /// </summary>
        internal static string yourBalance {
            get {
                return ResourceManager.GetString("yourBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piri Coin Bakiyeniz:.
        /// </summary>
        internal static string yourPiriBalance {
            get {
                return ResourceManager.GetString("yourPiriBalance", resourceCulture);
            }
        }
    }
}
