//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PiriChainWalletDataBridge {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PiriChainWalletDataBridge.lang_en", typeof(lang_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        internal static string addNew {
            get {
                return ResourceManager.GetString("addNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Book.
        /// </summary>
        internal static string addressBook {
            get {
                return ResourceManager.GetString("addressBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your data will send Piri Blockchain and your Piri balance will spend. Are you sure continue operation?.
        /// </summary>
        internal static string areyousure_senddata {
            get {
                return ResourceManager.GetString("areyousure_senddata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure stop operation?.
        /// </summary>
        internal static string areYouSureStopOperation {
            get {
                return ResourceManager.GetString("areYouSureStopOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset.
        /// </summary>
        internal static string asset {
            get {
                return ResourceManager.GetString("asset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset.
        /// </summary>
        internal static string AssetName {
            get {
                return ResourceManager.GetString("AssetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block Height.
        /// </summary>
        internal static string blockHeight {
            get {
                return ResourceManager.GetString("blockHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block Producer.
        /// </summary>
        internal static string blockProducer {
            get {
                return ResourceManager.GetString("blockProducer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both Key And Value.
        /// </summary>
        internal static string bothKeyValue {
            get {
                return ResourceManager.GetString("bothKeyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation Count.
        /// </summary>
        internal static string confirmationCount {
            get {
                return ResourceManager.GetString("confirmationCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation Nodes.
        /// </summary>
        internal static string confirmationNodes {
            get {
                return ResourceManager.GetString("confirmationNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} addressbook is going to delete Are you sure?.
        /// </summary>
        internal static string confirmDelete {
            get {
                return ResourceManager.GetString("confirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed.
        /// </summary>
        internal static string confirmed {
            get {
                return ResourceManager.GetString("confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Address.
        /// </summary>
        internal static string createNewAddress {
            get {
                return ResourceManager.GetString("createNewAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Password.
        /// </summary>
        internal static string createNewPassword {
            get {
                return ResourceManager.GetString("createNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Table
        /// When Written Complex
        /// Custom SQL Query .
        /// </summary>
        internal static string createNewTableWhenCustomQueryAcrive {
            get {
                return ResourceManager.GetString("createNewTableWhenCustomQueryAcrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Data.
        /// </summary>
        internal static string customData {
            get {
                return ResourceManager.GetString("customData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System shows only first 100 records in your selected table or view. All records will have been sent during adding to the Pirichain..
        /// </summary>
        internal static string dataAnnoucement {
            get {
                return ResourceManager.GetString("dataAnnoucement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Time.
        /// </summary>
        internal static string dateTime {
            get {
                return ResourceManager.GetString("dateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        internal static string days {
            get {
                return ResourceManager.GetString("days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not Share with anyone For your Wallet SAFETY!.
        /// </summary>
        internal static string donotshaermnemonic {
            get {
                return ResourceManager.GetString("donotshaermnemonic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption Level.
        /// </summary>
        internal static string encrytionLevel {
            get {
                return ResourceManager.GetString("encrytionLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Password Below.
        /// </summary>
        internal static string enterNewPassword {
            get {
                return ResourceManager.GetString("enterNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Password Again Below .
        /// </summary>
        internal static string enterNewPasswordAgain {
            get {
                return ResourceManager.GetString("enterNewPasswordAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill All Fields!.
        /// </summary>
        internal static string errFillAllFields {
            get {
                return ResourceManager.GetString("errFillAllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insuffcient Balance.
        /// </summary>
        internal static string errInsufficientBalance {
            get {
                return ResourceManager.GetString("errInsufficientBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Must Be 5 Characters At Least!.
        /// </summary>
        internal static string errorMustbeLeast5Ch {
            get {
                return ResourceManager.GetString("errorMustbeLeast5Ch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords are not matched!.
        /// </summary>
        internal static string errorPasswordNotMatched {
            get {
                return ResourceManager.GetString("errorPasswordNotMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Password!.
        /// </summary>
        internal static string errWrongPass {
            get {
                return ResourceManager.GetString("errWrongPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Speed
        ///(Fee 2x)
        ///7s /1 Op.
        /// </summary>
        internal static string fastSpeed {
            get {
                return ResourceManager.GetString("fastSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee.
        /// </summary>
        internal static string fee {
            get {
                return ResourceManager.GetString("fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pirichain Wallet And Data Bridge.
        /// </summary>
        internal static string frmEntrance_LblTitle {
            get {
                return ResourceManager.GetString("frmEntrance_LblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Password.
        /// </summary>
        internal static string frmEntrance_lblYourPassword {
            get {
                return ResourceManager.GetString("frmEntrance_lblYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string from {
            get {
                return ResourceManager.GetString("from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocks.
        /// </summary>
        internal static string globalBlocks {
            get {
                return ResourceManager.GetString("globalBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Transaction List.
        /// </summary>
        internal static string globalTransactionList {
            get {
                return ResourceManager.GetString("globalTransactionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Transactions.
        /// </summary>
        internal static string globalTransactions {
            get {
                return ResourceManager.GetString("globalTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        internal static string hours {
            get {
                return ResourceManager.GetString("hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        internal static string key {
            get {
                return ResourceManager.GetString("key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        internal static string label {
            get {
                return ResourceManager.GetString("label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string lang {
            get {
                return ResourceManager.GetString("lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string left {
            get {
                return ResourceManager.GetString("left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lightning
        ///(Fee 5x)
        ///3s /1 Op.
        /// </summary>
        internal static string lightingSpeed {
            get {
                return ResourceManager.GetString("lightingSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading... Please Wait....
        /// </summary>
        internal static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string menuAbout {
            get {
                return ResourceManager.GetString("menuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Book.
        /// </summary>
        internal static string menuAddressBook {
            get {
                return ResourceManager.GetString("menuAddressBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Wallet.
        /// </summary>
        internal static string menuAddWallet {
            get {
                return ResourceManager.GetString("menuAddWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        internal static string menuDatabase {
            get {
                return ResourceManager.GetString("menuDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Wallet.
        /// </summary>
        internal static string menuDeleteWallet {
            get {
                return ResourceManager.GetString("menuDeleteWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get My Wallet Keywords.
        /// </summary>
        internal static string menuGetMyWords {
            get {
                return ResourceManager.GetString("menuGetMyWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore My Wallet.
        /// </summary>
        internal static string menuRestoreMyWallet {
            get {
                return ResourceManager.GetString("menuRestoreMyWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Wallet.
        /// </summary>
        internal static string menuSelectWallet {
            get {
                return ResourceManager.GetString("menuSelectWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Piri Or Token.
        /// </summary>
        internal static string menuSendCoin {
            get {
                return ResourceManager.GetString("menuSendCoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallets.
        /// </summary>
        internal static string menuWallet {
            get {
                return ResourceManager.GetString("menuWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Added Successfully!.
        /// </summary>
        internal static string messageAddressAdded {
            get {
                return ResourceManager.GetString("messageAddressAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Updated Successfully!.
        /// </summary>
        internal static string messageAddressUpdated {
            get {
                return ResourceManager.GetString("messageAddressUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer has been done successfully!.
        /// </summary>
        internal static string messageTransferSucc {
            get {
                return ResourceManager.GetString("messageTransferSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method.
        /// </summary>
        internal static string method {
            get {
                return ResourceManager.GetString("method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        internal static string minutes {
            get {
                return ResourceManager.GetString("minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Wallet Added Successfully! You can select new wallet top menu !.
        /// </summary>
        internal static string msgWalletAddedSucc {
            get {
                return ResourceManager.GetString("msgWalletAddedSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Transactions.
        /// </summary>
        internal static string myTransactions {
            get {
                return ResourceManager.GetString("myTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Encryption.
        /// </summary>
        internal static string noEncryption {
            get {
                return ResourceManager.GetString("noEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Speed
        ///(Fee 1x )  
        ///10s /1 Op.
        /// </summary>
        internal static string normalSpeed {
            get {
                return ResourceManager.GetString("normalSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t Send if Tx Field Exists.
        /// </summary>
        internal static string notSendIfTxExists {
            get {
                return ResourceManager.GetString("notSendIfTxExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Key.
        /// </summary>
        internal static string onlyKey {
            get {
                return ResourceManager.GetString("onlyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending Data Operation ended!.
        /// </summary>
        internal static string operationEnd {
            get {
                return ResourceManager.GetString("operationEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Speed.
        /// </summary>
        internal static string operationSpeed {
            get {
                return ResourceManager.GetString("operationSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string pause {
            get {
                return ResourceManager.GetString("pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Key.
        /// </summary>
        internal static string pubKey {
            get {
                return ResourceManager.GetString("pubKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt Address.
        /// </summary>
        internal static string receipt {
            get {
                return ResourceManager.GetString("receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive.
        /// </summary>
        internal static string receive {
            get {
                return ResourceManager.GetString("receive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reamining Time To End:.
        /// </summary>
        internal static string remainingTimeToEnd {
            get {
                return ResourceManager.GetString("remainingTimeToEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rescue My Wallet.
        /// </summary>
        internal static string RescueMyWallet {
            get {
                return ResourceManager.GetString("RescueMyWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string result {
            get {
                return ResourceManager.GetString("result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        internal static string seconds {
            get {
                return ResourceManager.GetString("seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send All Fields.
        /// </summary>
        internal static string sendAllFields {
            get {
                return ResourceManager.GetString("sendAllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Only Below Selected Fields.
        /// </summary>
        internal static string sendOnlyBelowFields {
            get {
                return ResourceManager.GetString("sendOnlyBelowFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature.
        /// </summary>
        internal static string signature {
            get {
                return ResourceManager.GetString("signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approx Spend Fee:.
        /// </summary>
        internal static string spendFee {
            get {
                return ResourceManager.GetString("spendFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string stop {
            get {
                return ResourceManager.GetString("stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction.
        /// </summary>
        internal static string transaction {
            get {
                return ResourceManager.GetString("transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Transaction List.
        /// </summary>
        internal static string transactionList {
            get {
                return ResourceManager.GetString("transactionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Page.
        /// </summary>
        internal static string transferInterface {
            get {
                return ResourceManager.GetString("transferInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validators.
        /// </summary>
        internal static string validators {
            get {
                return ResourceManager.GetString("validators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string value {
            get {
                return ResourceManager.GetString("value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Balance:.
        /// </summary>
        internal static string yourBalance {
            get {
                return ResourceManager.GetString("yourBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Piri Coin Balance:.
        /// </summary>
        internal static string yourPiriBalance {
            get {
                return ResourceManager.GetString("yourPiriBalance", resourceCulture);
            }
        }
    }
}
